In [1]:
a=2
b=4
c=a+b
print(c)

6


In [4]:
a=5
b=10
c=7
if a>b:
  print("a is greater")
if b>c:
  print("b is greater")
else:
  print("c is greater")

b is greater


In [4]:
a=[3,5,7,9]
b=[]
for i in range(len(a)-1,-1,-1):
  b.append(a[i])
print(b)

[9, 7, 5, 3]


In [21]:
a=1
b=1
while b<50:
  print(b)
  a,b=b,a+b

1
2
3
5
8
13
21
34


In [0]:
import numpy as np

In [14]:
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [21]:
a.shape

(2, 3)

In [23]:
a.ndim

2

In [24]:
b=np.array([1,2,3])
b

array([1, 2, 3])

In [25]:
a = np.array([[1,2],[3,4]]) 
b = np.array([[11,12],[13,14]]) 
np.dot(a,b)

array([[37, 40],
       [85, 92]])

In [26]:
x = [1, 2, 3]
y = [4, 5, 6]
np.cross(x, y)


array([-3,  6, -3])

In [0]:
a = np.array([[1,2],[3,4]]) 
b = np.array([[11,12],[13,14]]) 
c=a+b

In [38]:
a = np.random.randn(3,3)
a

array([[ 0.32203314,  0.06885365, -0.74912966],
       [ 2.29294918,  0.37054293, -1.38412884],
       [-0.97199845, -0.96088964,  1.67466849]])

In [39]:
b = np.random.randn(3,3)
b

array([[-0.22770646, -0.15617067, -0.18779782],
       [ 0.64944361,  1.71422074,  0.12209105],
       [ 0.88917248,  1.44634125,  1.48999974]])

In [124]:
result1=np.dot(a,b)
result1

array([[-0.69471794, -1.01575891, -1.16827371],
       [-1.51220189, -1.72482168, -2.4477225 ],
       [ 1.08635583,  0.92676283,  2.56047878]])

In [43]:
result2=np.cross(a,b)
result2


array([[-0.12992265,  0.23105879, -0.03461371],
       [ 2.41794235, -1.1788622 ,  3.6899743 ],
       [-3.85386743,  2.93734657, -0.55144484]])

In [125]:
result3=np.add(a,b)
result3

array([[ 0.09432667, -0.08731702, -0.93692748],
       [ 2.94239278,  2.08476367, -1.2620378 ],
       [-0.08282597,  0.48545162,  3.16466823]])

In [56]:

X = np.random.randn(3,3)
THETA = np.random.randn(3,3)
print (X.dot(THETA))


[[-0.01371787  2.08054094  0.07962294]
 [-0.94039253  0.10068743  5.34717206]
 [ 0.45398197 -1.44273262  0.48467645]]


In [78]:
import pandas as pd
d=pd.read_csv("Iris.csv")
d.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           NaN            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [62]:
d=pd.read_csv("https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv")
d.head()

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [101]:
j=d.dropna()
j.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa
5   6            5.4           3.9            1.7           0.4  Iris-setosa

In [100]:
k=d.fillna(d.mean())
k.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1      3.051007            1.4           0.2  Iris-setosa
1   2            4.9      3.000000            1.4           0.2  Iris-setosa
2   3            4.7      3.200000            1.3           0.2  Iris-setosa
3   4            4.6      3.100000            1.5           0.2  Iris-setosa
4   5            5.0      3.600000            1.4           0.2  Iris-setosa

In [103]:
SepalWidthCm=k['SepalWidthCm']
SepalWidthCm.head()

0    3.051007
1    3.000000
2    3.200000
3    3.100000
4    3.600000
Name: SepalWidthCm, dtype: float64

In [117]:
k.iloc[:2, [0,1,2,3]]

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm
0   1            5.1      3.051007            1.4
1   2            4.9      3.000000            1.4

In [127]:
k=k.loc[:,['SepalWidthCm']]
k.head()


SepalWidthCm
0      3.051007
1      3.000000
2      3.200000
3      3.100000
4      3.600000

In [129]:
df1 = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],'data1': range(7)})
df1

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6

In [131]:
df2 = pd.DataFrame({'key': ['a', 'b', 'd'],'data2': range(3)})
df2

key  data2
0   a      0
1   b      1
2   d      2

In [137]:
con=pd.concat([df1,df2],axis=1)
con

key  data1  key  data2
0   b      0    a    0.0
1   b      1    b    1.0
2   a      2    d    2.0
3   c      3  NaN    NaN
4   a      4  NaN    NaN
5   a      5  NaN    NaN
6   b      6  NaN    NaN

In [139]:
con1=pd.concat([df1,df2],axis=1,ignore_index=True)
con1

0  1    2    3
0  b  0    a  0.0
1  b  1    b  1.0
2  a  2    d  2.0
3  c  3  NaN  NaN
4  a  4  NaN  NaN
5  a  5  NaN  NaN
6  b  6  NaN  NaN